package-mode = false

[project]
name = "tcc-ml-investimentos"
version = "0.1.0"
description = "Supervised machine learning for stock selection and portfolio backtesting"
authors = [
    {name = "Guilherme Hachimine",email = "gui.hachimine@gmail.com"}
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "pandas (>=2.2,<3)",
    "numpy (>=2.4.6,<3.0.0)",
    "yfinance (>=1.4.1,<2.0.0)",
    "scikit-learn (>=1.9.0,<2.0.0)",
    "xgboost (>=3.2.0,<4.0.0)",
    "mlflow (>=3.13.0,<4.0.0)",
    "matplotlib (>=3.10.9,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "jupyter (>=1.1.1,<2.0.0)",
    "ipykernel (>=7.2.0,<8.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"